# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^static/app.*\.css$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: pngcrush
        name: pngcrush
        language: system
        entry: bash -c 'xargs -I{} <<< "$@" pngcrush -rem allb -brute -reduce -ow {}'
        types: [png]
      - id: jpegoptim
        name: jpegoptim
        language: system
        entry: bash -c 'xargs -I{} <<< "$@" jpegoptim {}'
        types: [jpeg]
